#include "SafeRLMonitorFor2RobotsLib.h"
/**************************
 * ControllerFor2.c
 * Generated by KeYmaera X
 **************************/
/**************************
 * ControllerFor2.c
 * Generated by KeYmaera X
 **************************/
#include <math.h>
#include <stdbool.h>
typedef struct input {
  long double DirMX;
  long double DirMY;
  long double Velocity;
} input;
typedef struct verdict { int id; long double val; } verdict;
/* Computes distance to safety boundary on prior and current state (>=0 is safe, <0 is unsafe) */
verdict boundaryDist(state pre, state curr, const parameters* const params) {
  verdict result = { .id=(((!(1.0L)) || ((curr.Velocity >= 0.0L) && ((((!(curr.Velocity == 0.0L)) || ((curr.DirMX == 0.0L) && (curr.DirMY == 0.0L))) && ((!((curr.DirMX == 0.0L) && (curr.DirMY == 0.0L))) || (curr.Velocity == 0.0L))) && (((((pow(((params->DiffAX)*(params->DiffAX))+((params->DiffAY)*(params->DiffAY)),0.5L))-((curr.Velocity)*(params->STEPTSRL)))-((params->MAXVELOA)*(params->STEPTSRL)) > params->MINDISTA) || (curr.Velocity == 0.0L)) && ((((pow(((params->DiffBX)*(params->DiffBX))+((params->DiffBY)*(params->DiffBY)),0.5L))-((curr.Velocity)*(params->STEPTSRL)))-((params->MAXVELOB)*(params->STEPTSRL)) > params->MINDISTB) || (curr.Velocity == 0.0L)))))) && ((curr.DirMX == curr.DirMX) && ((curr.DirMY == curr.DirMY) && (curr.Velocity == curr.Velocity))) ? 1 : -1), .val=(((!(1.0L)) || ((curr.Velocity >= 0.0L) && ((((!(curr.Velocity == 0.0L)) || ((curr.DirMX == 0.0L) && (curr.DirMY == 0.0L))) && ((!((curr.DirMX == 0.0L) && (curr.DirMY == 0.0L))) || (curr.Velocity == 0.0L))) && (((((pow(((params->DiffAX)*(params->DiffAX))+((params->DiffAY)*(params->DiffAY)),0.5L))-((curr.Velocity)*(params->STEPTSRL)))-((params->MAXVELOA)*(params->STEPTSRL)) > params->MINDISTA) || (curr.Velocity == 0.0L)) && ((((pow(((params->DiffBX)*(params->DiffBX))+((params->DiffBY)*(params->DiffBY)),0.5L))-((curr.Velocity)*(params->STEPTSRL)))-((params->MAXVELOB)*(params->STEPTSRL)) > params->MINDISTB) || (curr.Velocity == 0.0L)))))) && ((curr.DirMX == curr.DirMX) && ((curr.DirMY == curr.DirMY) && (curr.Velocity == curr.Velocity))) ? 1.0L : -1.0L) }; return result;
}
/* Evaluates monitor condition in prior and current state */
bool monitorSatisfied(state pre, state curr, const parameters* const params) {
  return boundaryDist(pre,curr,params).val >= 0.0L;
}
/* Run controller `ctrl` monitored, return `fallback` if `ctrl` violates monitor */
state monitoredCtrl(state curr, const parameters* const params, const input* const in,
                    state (*ctrl)(state,const parameters* const,const input* const), state (*fallback)(state,const parameters* const,const input* const)) {
  state pre = curr;
  state post = (*ctrl)(pre,params,in);
  if (!monitorSatisfied(pre,post,params)) return (*fallback)(pre,params,in);
  else return post;
}
//automatically generated monitor function for matlab
int HCMonitor(struct state pre,struct state post,struct parameters params) {
return monitorSatisfied(pre, post, &params);
}
